module.exports = {
  title: "호키포키",
  description: "안녕하세요 백엔드 개발자 함석호의 블로그입니다.",
  author: "Forkyy",
  siteUrl: "https://forkyy-dev.site/",
  links: {
    github: "https://github.com/forkyy-dev",
    linkedIn: "",
    facebook: "",
    twitter: "",
    x: "",
    instagram: "",
    medium: "",
    blogger: "",
    email: "mailto:forkyy.dev@gmail.com",
    resume: "",
    link: "",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "devHudi/gatsby-starter-hoodie",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
